Mod 1
ipotemkin/skypro-music-player-front pull request #1
Opened 2022-09-22 21:29 UTC by ipotemkin

Исправления после первой пачки замечаний :)

2022-09-23 07:25 UTC, mrerberg commented
> logo.svg Нужен файл?

PIN: Это иконка приложения 

А почему лого редакса?) Такую иконку можно в папку public утащить

2022-09-23 07:26 UTC, mrerberg commented
> IPlayerState

 

Венгерская нотация - рудимент. Мы пользуемся редакторами кода и

по контексту понятно, что мы обращаемся к интерфейсу или типу

 

PIN:  Услышал. Но, позволь, в этом проекте не менять


Да, окей

2022-09-23 07:26 UTC, mrerberg commented
> /* body {

 

Почему?

 

PIN: Не знаю. Так привык. А как по другому?

Так код закомментирован, в этом была проблема. Он тогда не используется

2022-09-23 07:27 UTC, mrerberg commented
> TracksPage.tsx

Файл с компонентом проще называть index, тогда будет короче путь
PIN: Sorry, мне так удобнее, когда файл называется так же, как компонент.

Принято

2022-09-23 07:31 UTC, mrerberg commented
> Tracks

 

Данный компонент содержит некоторые компоненты, которые можно

было бы вынести в общий компонент Page. Там бы я хранил общий Layout (SideMenu, Sidebar и прочее). А уже в виде children поступал бы контент для

страницы

 

PIN: Идею, кажется, понял, но не понимаю, какие выгоды это может принести в моем проекте. Возможно, я не понял идею. Получился бы еще один промежуточный компонент, который бы использовался только с Tracks в качестве children.

Согласен, компонент Tracks вышел немного корявым. Но как его поправить, не понимаю ((


---

Обычно делают компонент Layout или просто Page. В твоем случае он будет выглядеть как-то так (накидываю примерно). Потому что Tracks по семантике как-то должен быть связан с треками (список треков и тд), а по факту это общий компонент страницы

```ts
const Page = ({ title, children }) => {
  <div>
    <h1>{title}</h1>
    <SideBar>
    
    <div>
      {children}
    </div>
  <div>
}
```

2022-09-23 07:32 UTC, mrerberg commented
> assets

 

> https://github.com/core-ds/icons/blob/master/packages/classic/src/AccountAddMBlackIcon.tsx

 

Иконки рекомендую использовать вот так. Просто и удобно.

Переиспользуемо

 

PIN: Супер! Пробовал скачать – у меня не получилось. Опять, видимо, приколы с моей версией npm

---

Качать не нужно, я привел пример именно кода, как сделать иконки

2022-09-23 07:43 UTC, mrerberg requested changes

2022-09-23 07:43 UTC, mrerberg commented on src/features/LoginForm/LoginForm.tsx
> +    logout()
Каждый раз при заходе на страницу логина, узер вылогинивается, если был до этого авторизован? Кажется хаком. Обычно, если пользователь авторизован, ему, с помощью роутера, не дают зайти на страницу логина - редиректят. А вылогинивают там, где это нужно. По кнопке "Выйти", к примеру

2022-09-23 07:43 UTC, mrerberg commented on src/features/LoginForm/LoginForm.tsx
>          <p style={{ color: 'red' }}><small>{ error && getErrorMessage(error) }</small></p>}
Хардкод стилей

2022-09-23 07:43 UTC, mrerberg commented on src/features/LoginForm/validators.ts
> +  // Здесь может быть валидатор username
Зачем этот коммент?

2022-09-23 07:43 UTC, mrerberg commented on src/features/LoginForm/validators.ts
> +  // Здесь может быть валидатор пароля
Зачем этот коммент?

2022-09-23 07:43 UTC, mrerberg commented on src/models.ts
> +export interface ILoginFormState {
```
export interface ILoginFormState {
  username: {
    value: string;
    error: boolean;
  };
  password: {
    value: string;
    repeatedValue: string;
    error: boolean;
    repeatedValueError: boolean
  };
  register: boolean;
  enableSubmit: boolean;
}
```

2022-09-23 07:43 UTC, mrerberg commented on src/models.ts
> +  enableSubmit: boolean;
Мне кажется, это вообще можно не хранить в состоянии формы, а просто значение вычислять

2022-09-23 07:43 UTC, mrerberg commented on src/routes.tsx
> +  //       <Route path={ROUTES.tracks} element={ <TracksPage /> } />
По главному url у тебя должен показываться TracksPage

<Route path="/" element={ TracksPage } />

2022-09-23 07:43 UTC, mrerberg commented on src/routes.tsx
> +  //       <Route path={ROUTES.tracks} element={ <TracksPage /> } />
Попробуй это пофиксить, и цикл мб уйдет

2022-09-23 08:23 UTC, ipotemkin commented
> > /* body {
> 
> Почему?
> 
> PIN: Не знаю. Так привык. А как по другому?
> 
> Так код закомментирован, в этом была проблема. Он тогда не используется

Забыл, что потом закомментировал :) Теперь удалил

2022-09-23 08:30 UTC, ipotemkin commented
> > Tracks
> 
> Данный компонент содержит некоторые компоненты, которые можно
> 
> было бы вынести в общий компонент Page. Там бы я хранил общий Layout (SideMenu, Sidebar и прочее). А уже в виде children поступал бы контент для
> 
> страницы
> 
> PIN: Идею, кажется, понял, но не понимаю, какие выгоды это может принести в моем проекте. Возможно, я не понял идею. Получился бы еще один промежуточный компонент, который бы использовался только с Tracks в качестве children.
> 
> Согласен, компонент Tracks вышел немного корявым. Но как его поправить, не понимаю ((
> 
> Обычно делают компонент Layout или просто Page. В твоем случае он будет выглядеть как-то так (накидываю примерно). Потому что Tracks по семантике как-то должен быть связан с треками (список треков и тд), а по факту это общий компонент страницы
> 
> ```ts
> const Page = ({ title, children }) => {
>   <div>
>     <h1>{title}</h1>
>     <SideBar>
>     
>     <div>
>       {children}
>     </div>
>   <div>
> }
> ```

Есть одна проблемка - это пропс data, который формируется внутри Tracks, но также используется в Player. Я предполагал Sidemenu, Sidebar и Player вынести в Page. Но data в Player ломает логику ((

2022-09-23 08:37 UTC, ipotemkin commented on src/features/LoginForm/LoginForm.tsx
>          <p style={{ color: 'red' }}><small>{ error && getErrorMessage(error) }</small></p>}
Исправил

2022-09-23 08:38 UTC, ipotemkin commented on src/features/LoginForm/validators.ts
> +  // Здесь может быть валидатор username
удалил

2022-09-23 08:38 UTC, ipotemkin commented on src/features/LoginForm/validators.ts
> +  // Здесь может быть валидатор пароля
Удалил

2022-09-23 08:41 UTC, ipotemkin commented on src/models.ts
> +export interface ILoginFormState {
Спасибо за вариант! Но мне было удобнее все ошибки собрать в одно место. Их так проще обнулять.

2022-09-23 08:42 UTC, ipotemkin commented on src/models.ts
> +  enableSubmit: boolean;
возможно, но мне так показалось проще.

2022-09-23 08:48 UTC, ipotemkin commented on src/routes.tsx
> +  //       <Route path={ROUTES.tracks} element={ <TracksPage /> } />
Это не помогло. Помогло то, что я вынес <Route path={ROUTES.login} element={ <LoginPage /> } /> за пределы блока с ProtectedRoute.

2022-09-23 08:50 UTC, ipotemkin commented on src/features/LoginForm/LoginForm.tsx
> +    logout()
Но тогда придется делать два действия logout и редирект на LoginPage?

2022-09-23 21:24 UTC, ipotemkin commented
Часть иконок превратил в компоненты. Понравилось. Код прозрачнее.
Но не понимаю, можно ли изменять размеры иконок. У меня не получилось. Если я меняю width, height, viewBox, то меняется окошко, а само изображение иконки не меняется ((

2022-09-24 14:08 UTC, mrerberg commented on src/features/LoginForm/LoginForm.tsx
> +    logout()
Ничего страшного. Вообще, необязательно делать редирект. Если правильно работает ProtectedeRoute, то при исчезновении признака логина редирект сам автоматом произойдет

2022-09-24 14:09 UTC, mrerberg commented on src/models.ts
> +export interface ILoginFormState {
Можно запихнуть тогда все ошибки в поле  errors

2022-09-24 14:09 UTC, mrerberg commented on src/routes.tsx
> +  //       <Route path={ROUTES.tracks} element={ <TracksPage /> } />
А, логично :D

2022-09-24 14:10 UTC, mrerberg commented
> > > Tracks
> > 
> > 
> > Данный компонент содержит некоторые компоненты, которые можно
> > было бы вынести в общий компонент Page. Там бы я хранил общий Layout (SideMenu, Sidebar и прочее). А уже в виде children поступал бы контент для
> > страницы
> > PIN: Идею, кажется, понял, но не понимаю, какие выгоды это может принести в моем проекте. Возможно, я не понял идею. Получился бы еще один промежуточный компонент, который бы использовался только с Tracks в качестве children.
> > Согласен, компонент Tracks вышел немного корявым. Но как его поправить, не понимаю ((
> > Обычно делают компонент Layout или просто Page. В твоем случае он будет выглядеть как-то так (накидываю примерно). Потому что Tracks по семантике как-то должен быть связан с треками (список треков и тд), а по факту это общий компонент страницы
> > ```ts
> > const Page = ({ title, children }) => {
> >   <div>
> >     <h1>{title}</h1>
> >     <SideBar>
> >     
> >     <div>
> >       {children}
> >     </div>
> >   <div>
> > }
> > ```
> 
> Есть одна проблемка - это пропс data, который формируется внутри Tracks, но также используется в Player. Я предполагал Sidemenu, Sidebar и Player вынести в Page. Но data в Player ломает логику ((

А в чем там загвоздка? не понимаю

2022-09-24 14:11 UTC, mrerberg commented
> Часть иконок превратил в компоненты. Понравилось. Код прозрачнее. Но не понимаю, можно ли изменять размеры иконок. У меня не получилось. Если я меняю width, height, viewBox, то меняется окошко, а само изображение иконки не меняется ((

Потому как width и height захадкожены в коде иконки, скорее всего. А так да, можно менять динамически размеры

2022-09-24 14:26 UTC, mrerberg requested changes

2022-09-24 14:26 UTC, mrerberg commented on src/features/icons/LoopIcon.tsx
> +    width="20"
Вот тут не нужен хардкод, расширяй с помощью пропс

2022-09-24 14:26 UTC, mrerberg commented on src/routes.tsx
> +        <Route path={ROUTES.home} element={ <TracksPage /> } />
Форматни код, пожалуйста, а то есть вертикальные отступы между элементами, то нет

2022-09-24 17:53 UTC, ipotemkin commented on src/routes.tsx
> +        <Route path={ROUTES.home} element={ <TracksPage /> } />
Не понял, о чем ты

2022-09-24 18:00 UTC, ipotemkin commented on src/features/icons/LoopIcon.tsx
> +    width="20"
Так я сделал ровно, как в ссылке, которую ты мне присылал.
Попробовал править на элементе HeartIcon – это то, что ты имел в виду?

2022-09-24 18:16 UTC, ipotemkin commented on src/features/LoginForm/LoginForm.tsx
> +    logout()
Пробовал, но так код только усложняется. К тому же, при выборе меню "Выход" мы переходим на LoginForm, но не происходит logout

2022-09-24 20:21 UTC, ipotemkin commented on src/features/icons/LoopIcon.tsx
> +    width="20"
Пришлось вернуть все назад, так как не работало правильно ((

2022-09-26 07:39 UTC, merged